###############################
# Builder
###############################
FROM golang:1.15 as builder
# -----------------------
# ARG
ARG WORKDIR
ARG APP_NAME
# -----------------------
WORKDIR $WORKDIR
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go get -u github.com/cosmtrek/air
EXPOSE $PORT

CMD air -c .air.toml
