version: "3"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile-dev
      args:
        APP_NAME: $APP_NAME
        WORKDIR: $WORKDIR
    ports:
      - 3000:3000
    depends_on:
      - db

    volumes:
      - .:${WORKDIR}

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
