/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/user": {
    /** ログインユーザ情報 */
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["UserResponse"];
          };
        };
      };
    };
  };
};

export type components = {
  schemas: {
    User: {
      /** @description ユーザ名 */
      name: string;
      /** @description アバター画像パス */
      avatar: string;
      /** @description user id */
      id: string;
      /** @description メールアドレス */
      email: string;
    };
    UserResponse: {
      user: components["schemas"]["User"];
    };
  };
};

export type operations = {};

export type external = {};
